Setup and readme improvements
hestiaAI/Argonodes pull request #28
Opened 2022-04-29 09:34 UTC by valentinoli

2022-05-02 08:21 UTC, Amustache requested changes
cf. our private discussion

2022-05-02 08:21 UTC, Amustache commented on .pre-commit-config.yaml
> +        name: Strip notebook output
As stated, I think I'd rather not strip the Notebook, because it is supposed to be a readable example.

2022-05-02 08:21 UTC, Amustache commented on examples/notebook/Example.ipynb
> -   "outputs": [
(for the whole file) as stated, keep the outputs, it's by design (;

2022-05-02 08:21 UTC, Amustache commented on requirements.txt
> +pylint
Rename into: `requirements-dev.txt`

2022-05-02 08:21 UTC, Amustache commented on .gitattributes
> +examples/notebook/Example.ipynb filter= diff=
Not sure about that one, to be tested.

2022-05-02 08:21 UTC, Amustache commented on README.md
> +## Setup
```suggestion
## Setup for development
```

2022-05-02 08:21 UTC, Amustache commented on README.md
> +```
Tab

2022-05-02 08:21 UTC, Amustache commented on README.md
> +```
Tab

2022-05-02 08:21 UTC, Amustache commented on README.md
> +```
Tab

2022-05-02 08:21 UTC, Amustache commented on README.md
> +```
Tab

2022-05-18 13:38 UTC, Amustache commented
Hello @valentinoli !

So, as a few changes have been made in the master branch thanks to your help, I will close that PR if it's okay for you. Kindly let me know.

However, feel free to review the new README/requirements if you feel like it.

Thank you!

2022-05-18 14:57 UTC, valentinoli commented
> Hello @valentinoli !
> 
> So, as a few changes have been made in the master branch thanks to your help, I will close that PR if it's okay for you. Kindly let me know.
> 
> However, feel free to review the new README/requirements if you feel like it.
> 
> Thank you!

That's fine with me :)

2022-05-18 14:57 UTC, closed without merging